name: Request Info

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  issues: write
  pull-requests: write

jobs:
  request-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          match-templates: "true"
