name: triage

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  issues: write
  pull-requests: write

jobs:
  request-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: mise run init

      - name: Run build
        run: mise run build

      - name: Run request info
        uses: ./
        with:
          match-templates: "true"
